version: '3.4'
services:
  reshopper-tests:
    image: TestRunnerProject
    volumes:
      - ./:/src
    build:
      target: testrunner
      context: .
      dockerfile: Dockerfile
      args:
        CODE_VERSION: ${CODE_VERSION-not_defined}